### ISSUE TITLE
Number of ins and outs for BoilerTurbogenerator

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#14]
**Describe the bug**
In biosteam v2.0.1, the numbers of ins and outs for `BoilerTurbogenerator` are both 3 (in v1.0.8, there are only 2 ins and 2 outs). This seems to be creating empty ins and outs streams.

_However, I'm not sure if this unit is currently under development_

**Environment**
 - Python: v3.7.0
 - OS: macOS Catalina 10.15.3
 - BioSTEAM: v2.0.1

**Comment by yoelcortes** [comment]
Thanks for catching this bug, although the number of ins and outs should still be 3. Please update "pip install biorefineries==2.0.3" and "pip install biosteam==2.0.4".

The reason there are 3 inlet streams is because the corn stover biorefinery sends a stream of solids (which includes lignin and wastewater residues), a stream of methane from anaerobic digestion, and a stream of make-up water to the boiler turbogenerator. So to summarize....

ins: 
[0] Liquid/solid feed that will be burned.
[1] Gas that will be burned (optional).
[2] Make-up water (optional).  
outs :
[0] Emission from burned liquid/solid feed.
[1] Emission from burned gas feed (optional).
[2] Blowdown water (optional).

Note that its ok if stream [1] is missing. 

Side note:
You're right that with biosteam v1 there was only one feed to be burned. This is because there was a mistake in the cornstover where I did not include the methane from anaerobic digestion. I also had another bug that increased the heat of combustion for waste water, so luckily both cancelled out.

**Comment by yalinli2** [comment]
This looks good to me, thanks!!!
