### ISSUE TITLE
(Help wanted) Best practice to change one unit in a biorefinery

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#5]
If I just want to change one unit in an established biorefinery (e.g., change fermentation in the Humbird cornstover biorefinery), should I remake the whole biorefinery, or is there an easy way to swap out the original fermentation with the new one?

**Comment by yoelcortes** [comment]
It's not too hard to change an existing biorefinery configuration:

```python
>>> from biosteam.biorefineries.cornstover import system
>>> import biosteam as bst
>>> # Find saccharification and co-fermentation unit operation
>>> R301 = bst.find('R301') 
>>> # Create instance with the same input and output streams
>>> R301 = NewUnitOperationSubclass(ID=R301.ID, ins=R301.ins, outs=R301.outs) 
```
However, the System and TEA objects would need to be recreated for the biorefinery. One workaround for this is to (instead) cast the existing unit operation to another unit operation:
```python
>>> R301.__class__ = NewUnitOperation
```
But this may present odd problems later, and I do not recommend it. Preferably, its best if you copy the biosteam.biorefinery.cornstover.system script, and replace the line where R301 is created. Because this represents a new configuration, I also recommend setting the flowsheet name at the start of the script:
```python
>>> new_flowsheet = bst.Flowsheet('cornstover_with_new_fermentation_model')
>>> bst.find.set_flowsheet(new_flowsheet )
```
Hope this helps!

**Comment by yalinli2** [comment]
Thanks for the help! I agree it'll be easier to copy the script and change what I need to.
A side question - is the "NewUnitOperationSubclass" a really function or you just used it to indicate whatever new unit I want to create?

**Comment by yoelcortes** [comment]
"NewUnitOperationSubclass" just indicates the unit you'd like to create :)

**Comment by yalinli2** [comment]
Great, thanks! I'll close this off.
