### ISSUE TITLE
How to implement "_run" method in Unit subclasses?

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#6]
I was trying to create a very simple unit class using biosteam but ran into a lot of questions:

Let's assume I just want to make a tank (name=FakeTank), where there is only 1 ins and 1 outs and cost=0, here are my codes:
<img width="473" alt="FakeTank" src="https://user-images.githubusercontent.com/49011373/71772266-40b6f080-2f0e-11ea-8e47-e5d9cea3c640.png">

Then I try to create a FakeTank unit U101:
<img width="473" alt="U101" src="https://user-images.githubusercontent.com/49011373/71772296-c20e8300-2f0e-11ea-8aa0-164fdc2d31ae.png">

When I try to simulate U101, I got an error:
<img width="473" alt="Error" src="https://user-images.githubusercontent.com/49011373/71772308-f4b87b80-2f0e-11ea-8b83-3155dd26f1d5.png">

When I check the streams, the ins is what I want, but the outs is empty:
<img width="473" alt="Streams" src="https://user-images.githubusercontent.com/49011373/71772315-0863e200-2f0f-11ea-8062-43f99c53e2f2.png">

How should I modify the code to make this work?

Thanks!

**Comment by yalinli2** [comment]
**(Additional questions related to this thread)**
I noticed biosteam has some cool functions - copylike and copyflow, which appeared in the units module in the cornstover biorefinery (e.g., when creating the PretreatmentReactorSystem
 unit class, starting line 114):
<img width="473" alt="PretreatmentReactorSystem" src="https://user-images.githubusercontent.com/49011373/71772409-2120c780-2f10-11ea-88cd-f0368f58e505.png">

I tried to use similar codes when creating the FakeTank unit:
<img width="473" alt="FakeTank2" src="https://user-images.githubusercontent.com/49011373/71772448-aad09500-2f10-11ea-81f1-312a33a97456.png">

This time, I got an error suggesting 'Outs' has no attribute 'copylike'
<img width="473" alt="Error2" src="https://user-images.githubusercontent.com/49011373/71772463-d3f12580-2f10-11ea-87a5-e0b8f5f4837c.png">

How should I use the copylike function?

Additionally, what does the "_linkedstreams = True" do? I added that line because that appears in cornstover codes, and I thought that could be used to link outs to ins.

Also, I noticed some codes used the "link_streams" function, what will this do?

As a summary to my above questions, what is the simplest way to make a unit that has the same outs as ins?

Thanks!!!

**Comment by yalinli2** [comment]
**(More questions related to this thread on the factories module)**
I noticed some really cool codes the cornstover biorefinery used to batch-create units using the factories module of biosteam and an Excel spreadsheet:
<img width="652" alt="Batch-create units" src="https://user-images.githubusercontent.com/49011373/71772538-3565c400-2f12-11ea-879a-baf0fdfe327b.png">

Can you explain how this works? I couldn't really understand the raw codes in the factories module and additionally, I was baffled by the fact that/I wanted to know:
- Seems like not all units in the spreadsheet were used
- Only some units were created this way, was this intended to be a quick way for simple units?
- Is there anyway for me to check what units were created this way in the console?

Sorry I have a ton of questions... I tried to look at the tutorial but still couldn't figure these out. Let me know if the answers were somewhere in the tutorial , thanks!!!

**Comment by yoelcortes** [comment]
Nicee, its cool to see people trying to implement their own unit functions. Here is the explanation/fix to your bugs:

0. I noticed you replaced the `purchase_cost` and `installation_cost`, these are not abstract properties. Best if you do not replace them! Your purchase/installation cost will be 0 anyways if you don't add any purchase costs to the `_Cost` dictionary.

1. Comment 1: BioSTEAM doesn't let you directly set `ins` or `outs` because these are actually important objects that set the `source` and `sink` of Stream objects when set. The reference to the source and sink are what allow flowsheets to be created. You should use copylike instead (good job!).

2. Comment 2: The `ins` and `outs` attribute are actually lists of streams, so you would need to write:
```python
...
def _run(self):
    # Notice the commas
    feed, = self.ins 
    effluent, = self.outs
    # This should work
    effluent.copylike(feed) 
```
3. About linked streams... The `_linkedstreams` attribute is deprecated, you might be looking at older versions of BioSTEAM. The `link_streams` method of `Static` unit operations makes the input and output stream share data on the flow rates. The `_run` method in `Static` objects just copies T, P and phase from upstream to downstream, and the flow rates of both are always the same (so its faster!). Note that you can subclass from `Static` and replace the `_run` method, but the feed/effluent stream flow rates will always be linked. I'll use your fake tank as an example:
```python
from biosteam import *
from biosteam.units.decorators import cost

# Create Unit subclass
@cost(basis='Flow rate', units='kg/hr', cost=0, CE=522, n=0.6)
class FakeTank(units.Static): pass

```
Now lets test it:
```python
>>> Stream.species = Species('Water', 'Ethanol')
>>> feed = Stream('feed', Water=1, Ethanol=1)
>>> T1 = FakeTank('T1', ins=feed, outs='effluent')
>>> T1.show()
FakeTank: T1
ins...
[0] feed
    phase: 'l', T: 298.15 K, P: 101325 Pa
    flow (kmol/hr): Water    1
                    Ethanol  1
outs...
[0] effluent
    phase: 'l', T: 298.15 K, P: 101325 Pa
    flow (kmol/hr): Water    1
                    Ethanol  1
```

Hope this helps!

**Comment by yalinli2** [comment]
Great! Now it works!
Only one thing, I do need to keep the line:
`_N_outs = 1`

Otherwise I will get two out streams and trigger an error when simulating the unit:
<img width="311" alt="Two outs" src="https://user-images.githubusercontent.com/49011373/71780981-05a8d180-2f8f-11ea-9605-33d73d76b46f.png">

<img width="463" alt="Error" src="https://user-images.githubusercontent.com/49011373/71780993-27a25400-2f8f-11ea-9d4f-e0029c5fe258.png">

However I don't necessarily need to add:
`_N_ins = 1`

By adding a comma after feed/effluent, I can understand that two streams will be created for outs, but why there is only 1 ints? Is this because of some default setting?

Thanks!!!

**Comment by yoelcortes** [comment]
Ahh, yes, old commented code that shouldn't be there. Good catch, I'll remove it in the next BioSTEAM update.

As for the number of streams, I think you figured it out already:
```python
>>> from biosteam import Unit
>>> Unit._N_ins
1
>>> Unit._N_outs
2
```

**Comment by yalinli2** [comment]
Got it, thanks!!!
